### ISSUE TITLE
How to generate cutout graphics for custom components?

### ISSUE THREAD

**Issue by zzeneg** [skarrmann/horizon#1]
Hi,

I really like your approach with the bottom plate as a "case" and I'm trying to implement the same for my custom keyboard. As far as I understand you have custom footprints for the components you use which already have graphics on `Adhes` layers. I'm building a regular keyboard so I can't just use your footprints as I need 1.5U, 2U keys, stabilizers, etc. How did you add the graphics? Is it totally manual or is there some way to automate it?

**Comment by skarrmann** [comment]
Hello @zzeneg! Thank you for your question. I will update the readme with more details about how to create footprints that work with this board producer plugin, but for now hopefully this answer helps. Please let me know if you need any more details.

Your understanding of the footprints and the `Adhes` layers is correct.

I manually created the footprints. It takes a little bit of work. You might have already seen it, but there are some brief notes in the readme about how these footprints are configured: https://github.com/skarrmann/horizon#kicad-project-notes

Basically you need to create placeholder circular/oval SMD pads on the footprint to indicate the plate cutouts.

Here are some practices I followed when creating the keyswitch footprints with cutouts:

* For the mounting hole pads (like for the a keyswitch's center mounting hole and the two PCB mounting pins), copy the original pad and then change these settings:
    * Pad type: SMD
    * Copper: None
    * Size X: [use original pad size]
    * Technical layers: *disable all layers* except this one
        * B.Adhes ("B" is for bottom plate, "F" is for top plate)

* For the through-hole solder pads (like for the keyswitch's two pins), it's similar with a couple of adjustments. Copy the original pad and then change these settings:
    * Pad number: [set this to empty]
    * Pad type: SMD
    * Size X: [increase original pad size by 0.4mm - this extra space is accounts for possible solder/flux overflow]
    * Technical layers: *disable all layers* except this one
        * B.Adhes ("B" is for bottom plate, "F" is for top plate)

If you need cutout shapes other than a circles/ovals, you can draw graphics directly on the footprint on the `B.Adhes` and `F.Adhes` layers, using KiCad's graphic line / graphic arc tools. However, if you have a lot of cutouts drawn with graphics way, PCB manufacturers might charge extra for the plates due to milling time.

**Comment by zzeneg** [comment]
Awesome, thank you for such detailed instructions, as a total newbie in kicad I really appreciate it :)
